apiVersion: v1
kind: ReplicationController
metadata:
  name: messageservice-rc
spec:
  replicas: 32
  selector:
    app: messageservice
  template:
    metadata:
      name: messageservice-pod
      labels:
        app: messageservice
    spec:
      containers:
      - name: messageservice
        image: ehcontainer001.azurecr.io/messagingservice:v1
        imagePullPolicy: Always