apiVersion: v1
kind: ReplicationController
metadata:
  name: rulesetservice-rc
spec:
  replicas: 32
  selector:
    app: rulesetservice
  template:
    metadata:
      name: rulesetservice-pod
      labels:
        app: rulesetservice
    spec:
      containers:
      - name: rulesetservice
        image: ehcontainer001.azurecr.io/rulesetservice:v1
        imagePullPolicy: Always